### PR TITLE
Content update

### PR DESCRIPTION
**Pull request by enamchae**
- About page now displays photos from Worlds and basic statistics
  - I am unable to get a Google Maps embed on the page since it requires a Google billing account
  - I will try to add filters against the extraneous award entries
- Imported bitmoji for Yash I, Ethan H, Manoj K, Kaash G, and Mehmood A
- Removed members without bitmoji (Aditya R, Jason F, Arun I, Aditya D, John M, and Jai K)

### CODE REVIEW

**Comment by ArnavKaushik** [comment]
Try this code for the Google map:

```html
<div class="mapouter"><div class="gmap_canvas"><iframe width="500" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=conestoga%20high%20school&t=&z=15&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://www.embedgooglemap.net">embedgooglemap.net</a></div><style>.mapouter{position:relative;text-align:right;height:500px;width:500px;}.gmap_canvas {overflow:hidden;background:none!important;height:500px;width:500px;}</style></div>
```

**Comment by ArnavKaushik** [comment]
Also, some more Bitmojis have been added.

**Comment by enamchae** [comment]
This embed link works. Where on the page do you want the Google Map again?

Also remember to write about the VRC and Robotics Club if you can.

**Comment by ArnavKaushik** [comment]
Preferably underneath the gallery and statistics or maybe have three sections, with gallery, statistics, and map. Whatever looks the best. I am getting the VRC paragraph soon and will update the content spreadsheet sometime this night.

**Pull request merged**
