### PR TITLE
Content update

### PR DESCRIPTION
**Pull request by enamchae**
- Google Map was added to About page
- Imported bitmoji from John M, Arun I, Daniel R, and Kovid T
- Award counts no longer count awards from future events
- "Qualifier" and "Other" event counts have been merged since there is no reliable way to discern between them (and most Other events are qualifiers anyway)

### CODE REVIEW

**Comment by ArnavKaushik** [comment]
There seem to be some issues with data including Arun's picture being spelled incorrectly. Awards and events are taking a long time along with some not showing up, and the achievements section doesn't show anything. Also, the google map addition doesn't seem to be there.

**Comment by enamchae** [comment]
I've tested and cleared my cache on Chrome 79, Firefox 71, and EdgeHTML 18, and I'm not able to reproduce the achievements being slow/missing content or the Google Map being missing. I imagine the problem on your end is some JS file taking very long to load and then holding up the others from executing. I can try adding some loading signs to make it more user-friendly, but I can't trace the problem so I'm not sure what I can do to fix it.

Arun's icon has been renamed in my local project and I will commit it alongside the new page content (or earlier if you need me to).

**Comment by ArnavKaushik** [comment]
It seems to work now, it might be a cache issue or maybe it didn't have enough time to load. It looks great!

**Comment by ArnavKaushik** [comment]
Also added VRC paragraph in content spreadsheet.

**Pull request merged**
